### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by CrazyMarvin**

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
Is this safe to merge, @rockgem?

**Comment by rockgem** [comment]
> Is this safe to merge, @rockgem?

yes but we will need to manually edit the .csv file again to avoid translation errors.

**Comment by rockgem** [comment]
i just noticed, the .csv file no longer have that extra blank key, was there a change in crowdin config? did someone else fixed it? :D

**Comment by CrazyMarvin** [comment]
> i just noticed, the .csv file no longer have that extra blank key, was there a change in crowdin config? did someone else fixed it? :D

No, nothing that I am aware of.
But that are great news. 😁

**Pull request merged**
