### PR TITLE
add yodo banner ads on menu

### PR DESCRIPTION
**Pull request by rockgem**

### CODE REVIEW

**Comment by rockgem** [comment]
updated manifest files for yodo to detect the game's ads integration

**Review by rockgem — COMMENTED** [review]
its good af

**Comment by CrazyMarvin** [comment]
> its good af

Ah, I just noticed that you can select "game" directly inside of Godot. 👌
181439248-d6ff3841-8951-4109-839d-ad023c2d6d22

**Comment by rockgem** [comment]
> > its good af
> 
> Ah, I just noticed that you can select "game" directly inside of Godot. 👌 181439248-d6ff3841-8951-4109-839d-ad023c2d6d22

i think this only applies in godot 4.0.

**Pull request merged**
