### PR TITLE
Improved polish localization

### PR DESCRIPTION
**Pull request by damiansikora85**

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
Hi, what is the difference between your version and the old translation?

**Comment by damiansikora85** [comment]
It's looks like from auto-translate

**Comment by CrazyMarvin** [comment]
Oh, I see. Thanks for the info.

**Comment by CrazyMarvin** [comment]
Hey, thanks again for your help @damiansikora85. 🙏
I ordered some Pimple Popper stickers. Please send me your address via email if you would like to receive a few. ☺️

**Comment by CrazyMarvin** [comment]
Alright, they are on their way.

**Pull request merged**
