### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by CrazyMarvin**

### CODE REVIEW

**Comment by rockgem** [comment]
this is okay to be merge into development, it wont affect or change the translations anymore :))

**Comment by rockgem** [comment]
what are the conflicts about? this needs to be merge so i can work on adding the actual languages in-game :D

**Comment by CrazyMarvin** [comment]
> what are the conflicts about? this needs to be merge so i can work on adding the actual languages in-game :D

Do you see the conflicts on [https://github.com/Crazy-Marvin/PimplePopper/pull/94/conflicts](https://github.com/Crazy-Marvin/PimplePopper/pull/94/conflicts)?

**Comment by CrazyMarvin** [comment]
I will give you `write` access to the repo so that it is easier for you to fix the conflicts.

**Pull request merged**
