### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by STM3900**
I hope that's okay!

### CODE REVIEW

**Review by CrazyMarvin — APPROVED** [review]

**Comment by CrazyMarvin** [comment]
Thank you so much for your help. 👍
The PR looks good and I will merge it now. 
May I ping you again in some weeks when the app itself needs a French translation?

**Comment by STM3900** [comment]
I don't think i will be able to translate a whole app, but why not !

**Comment by CrazyMarvin** [comment]
The app itself won't have much text, don't worry. 😅
Thanks!

**Comment by CrazyMarvin** [comment]
Hey, thanks again for your help @STM3900. 🙏
I ordered some Pimple Popper stickers. Please send me your address via email if you would like to receive a few. ☺️

**Pull request merged**
