### PR TITLE
Added Italian translation

### PR DESCRIPTION
**Pull request by Giancarmine**

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
Awesome, thank you so much again @Giancarmine! 👍

**Comment by CrazyMarvin** [comment]
Hey, thanks again for your help @Giancarmine. 🙏
I ordered some Pimple Popper stickers. Please send me your address via email if you would like to receive a few. ☺️

**Comment by Giancarmine** [comment]
Wow!
I really love stickers, thank you for thing in me :rocket: :rocket: :rocket: 

Just a little thing, where can I find your email?
Is `marvin@poopjournal.rocks` the right one?

**Comment by CrazyMarvin** [comment]
> Wow!
> I really love stickers, thank you for thing in me :rocket: :rocket: :rocket: 
> 
> Just a little thing, where can I find your email?
> Is `marvin@poopjournal.rocks` the right one?
> 

Yes, that's the right one.

**Comment by CrazyMarvin** [comment]
Alright, they are on their way.

**Pull request merged**
