### PR TITLE
Update .crowdin.yml

### PR DESCRIPTION
**Pull request by Andrulko**
Update `crowdin.yml` to handle existing files with Crowdin+GitHub sync

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
Thank you so much for fixing this, @Andrulko! 😘

**Comment by CrazyMarvin** [comment]
Does Crowdin support the files in the `assets/i18n` folder too?
Do you recommend to disable the Crowdin Google Play integration as we are using the files from the `fastlane` folder now?

**Comment by Andrulko** [comment]
CSV? Yes. I can help with configuration but need to understand your expectations. You've got `translation.csv` currently. How should it be exported? Do you expect that Crowdin will create a separate CSV per language or do you need multilingual CSV (one file with column per language)?

I think it makes sense to deactivate the integration, since everything is handled by `fastlane` already.

**Comment by CrazyMarvin** [comment]
> CSV? Yes. I can help with configuration but need to understand your expectations. You've got `translation.csv` currently. How should it be exported? Do you expect that Crowdin will create a separate CSV per language or do you need multilingual CSV (one file with column per language)?

[Godot](https://docs.godotengine.org/de/stable/tutorials/i18n/internationalizing_games.html) creates files ending with `.translation`. Can Crowdin generate those files?
Because I did not find a way to do it I uploaded the list as .csv here on GitHub and as .xlsx on Crowdin.

> I think it makes sense to deactivate the integration, since everything is handled by `fastlane` already.

Alright, I just disabled it.

**Comment by Andrulko** [comment]
Unfortunately, it looks like `.translation` files are some encrypted binaries which cannot be easily translated :( 

Just realized that your CSV appears to be multilingual (besides `en`, you also have some existing `de` and `es` texts). Let's probably sync multilingual CSV (`translation.csv`) via GitHub, then you can generate `.translation` files on your side?

**Comment by Andrulko** [comment]
Do you really need to have 226 languages in your project? 🥲

**Comment by CrazyMarvin** [comment]
> Unfortunately, it looks like `.translation` files are some encrypted binaries which cannot be easily translated :(
> 
> Just realized that your CSV appears to be multilingual (besides `en`, you also have some existing `de` and `es` texts). Let's probably sync multilingual CSV (`translation.csv`) via GitHub, then you can generate `.translation` files on your side?

Yes, that sounds like a good approach. Let's try that please.

**Comment by CrazyMarvin** [comment]
> Do you really need to have 226 languages in your project? 🥲

No, that is a bit too much. 😅

I just saw the Top 30 option on Crowdin. Can I just select that? What happens to a language that is not in the Top 30 and has translations already? Will they stay?
top30

**Comment by Andrulko** [comment]
Hey,

I'm ready to continue with configuration :)

I propose to clear all languages on the right column -> add Top 30 languages -> save changes. If you want to add some extra language which had existing translations, please do that. All existing translations will be still kept even if the language was intentionally / accidentally removed👍

**Comment by CrazyMarvin** [comment]
> Hey,
> 
> I'm ready to continue with configuration :)
> 
> I propose to clear all languages on the right column -> add Top 30 languages -> save changes. If you want to add some extra language which had existing translations, please do that. All existing translations will be still kept even if the language was intentionally / accidentally removed👍

Done. 👌🏻

**Comment by Andrulko** [comment]
Thanks! I'll try playing with configuration and submit a PR

**Comment by Andrulko** [comment]
Ah, it's more challenging than I expected. I've stopped on this:
https://github.com/Andrulko/PimplePopper/blob/development/.crowdin.yml

Still, there is something to be improved. What do you think if the spreadsheet would be bi-lingual? Let's say:

| ID | EN | TARGET |

Exported files would be `translation.de.csv`, `translation.fr.csv` etc. It will definitely work perfectly :)

**Comment by CrazyMarvin** [comment]
If we cannot have everything in one file we have to go with that solution.
Thanks for figuring it out. 👍

**Comment by Andrulko** [comment]
Nevermind, I've found a reason:
https://github.com/Crazy-Marvin/PimplePopper/pull/54

Also, added columns headers for convenience :)

**Pull request merged**
