### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by CrazyMarvin**

### CODE REVIEW

**Comment by rockgem** [comment]
this commit has a very confusing merge conflicts lmao.

**Comment by rockgem** [comment]
> this commit has a very confusing merge conflicts lmao.

i will try fixing them tho

**Comment by rockgem** [comment]
**Conflicts needs fixing:**

- there are HEAD >>>>>> and "===========" everywhere and it is very difficult to track down which are to remove.

**Comment by CrazyMarvin** [comment]
May you please have a look, @Andrulko?

**Comment by rockgem** [comment]
merge conflicts resolved: 
I have completely removed the unnecessary .csv files since we are not using them in the game anyways. :D

**Review by rockgem — APPROVED** [review]
removed unnecessary files

**Comment by CrazyMarvin** [comment]
@JordanMotta used the .csv files for the translation workflow if I understood correctly. I am not sure about the details though. He sent me [this](https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/importing_translations.html).

**Comment by rockgem** [comment]
> 

yea, i know but there were unnecessary csv files that aren't event being used in the game. i think we only needed the translations.csv the other ones are not.

**Comment by CrazyMarvin** [comment]
> > 
> 
> yea, i know but there were unnecessary csv files that aren't event being used in the game. i think we only needed the translations.csv the other ones are not.

Alright, then I will merge now. 👍

**Comment by rockgem** [comment]
awesome!

**Comment by Andrulko** [comment]
I've seen it only now 😬 All good now? I see `<<<<<<< HEAD` in the source as well, probably it should be removed to prevent future conflicts?
https://github.com/Crazy-Marvin/PimplePopper/blob/development/assets/i18n/translation.csv#L1

**Comment by CrazyMarvin** [comment]
> I've seen it only now grimacing All good now? I see `<<<<<<< HEAD` in the source as well, probably it should be removed to prevent future conflicts? https://github.com/Crazy-Marvin/PimplePopper/blob/development/assets/i18n/translation.csv#L1

Thanks for checking, @Andrulko! 👍

I removed the `<<<<<<< HEAD` and `<<<<<<< development` entries. Please check, @rockgem & @Andrulko.

**Comment by Andrulko** [comment]
What about this?
https://github.com/Crazy-Marvin/PimplePopper/blob/development/assets/i18n/translation.csv#L2096

Same here:
https://github.com/Crazy-Marvin/PimplePopper/blob/development/assets/i18n/translation.csv#L2159

I tried importing your file to my test project, it's broken... I'll play a bit more with it

**Comment by Andrulko** [comment]
Just checked in LibreOffice Calc, it's not processed well. Everything goes wrong starting from this line:
https://github.com/Crazy-Marvin/PimplePopper/blob/development/assets/i18n/translation.csv#L24

It looks like content got duplicated

You have many column headers, there should be only one, I suppose. Here are a few samples:
https://github.com/Crazy-Marvin/PimplePopper/blob/development/assets/i18n/translation.csv#L26
https://github.com/Crazy-Marvin/PimplePopper/blob/development/assets/i18n/translation.csv#L51
https://github.com/Crazy-Marvin/PimplePopper/blob/development/assets/i18n/translation.csv#L82
https://github.com/Crazy-Marvin/PimplePopper/blob/development/assets/i18n/translation.csv#L82

**Comment by CrazyMarvin** [comment]
Oh, now I see it.
I just uploaded a fixed version, @rockgem and @Andrulko with commit 16a10d30a97cb711b5423b04966a92b74065e95e.

**Comment by Andrulko** [comment]
It looks much better now 😁

**Comment by CrazyMarvin** [comment]
Thank you so much for your help. 😘

**Pull request merged**
